### ISSUE TITLE
api_alipay_trade_query 遇到错误

### ISSUE THREAD

**Issue by Thinkgamer** [fzlee/alipay#34]
支付成功后，查看支付结果，遇到错误：
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/thinkgamer/Documents/github/travel/line/views.py", line 74, in check_pay
    response = alipay.api_alipay_trade_query(out_trade_no=order_id)  # response是一个字典
  File "/usr/local/lib/python3.5/dist-packages/alipay/__init__.py", line 284, in api_alipay_trade_query
    return self._verify_and_return_sync_response(raw_string, "alipay_trade_query_response")
  File "/usr/local/lib/python3.5/dist-packages/alipay/__init__.py", line 496, in _verify_and_return_sync_response
    sign = response["sign"]
KeyError: 'sign'

能否帮助解决一下

**Comment by Thinkgamer** [comment]
已经解决

**Comment by jeawy** [comment]
我猜初始化过程中，你把debug模式打开了，当debug模式打开之后，即使你在settings.py（或者你的配置文件中）设置的是支付宝的正式支付网关，debug调用的也是沙箱环境的网关。
我给作者的建议是：支付宝网关使用配置文件中的网关就可以了，不需要根据debug的不同设置来取不同的网关。
