### ISSUE TITLE
python2 AliPayException bug

### ISSUE THREAD

**Issue by cxinde** [fzlee/alipay#82]
python2.7环境下，如果遇到AliPayException异常，会出现如下错误：
~~~python
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/dist-packages/odoo/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 331, in getMessage
    msg = str(self.msg)
  File "/usr/local/lib/python2.7/dist-packages/alipay/exceptions.py", line 30, in __str__
    return self.to_unicode().encode('utf8')
  File "/usr/local/lib/python2.7/dist-packages/alipay/exceptions.py", line 28, in to_unicode
    return u"AliPayException: code:{}, message:{}".format(self.__code, self.__message.decode("utf8"))
AttributeError: 'dict' object has no attribute 'decode'
~~~
这里的self.__message是字典，所以直接decode的时候会报错。

建议修改_verify_and_return_sync_response函数在抛异常时message参数直接传入字符串类型：
~~~python
response = json.loads(raw_string)
# raise exceptions
if "sign" not in response.keys():
    result = response[response_type]
    raise AliPayException(
        code=result.get("code", "0"),
        # message=response
        message=raw_string
    )
~~~

**Comment by fzlee** [comment]
1.10.1 已修复
